- name: setting up catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: setup NPM source
    tags:
    - installation
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"
  
  - name: install nodejs
    tags:
    - installation
    ansible.builtin.yum:
      name: nodejs
      state: installed
  
  - name: check roboshop user exists or not
    tags:
    - installation
    ansible.builtin.command: id roboshop 
    register: output
    ignore_errors: true
  
  - name: create user roboshop
    tags:
    - installation
    ansible.builtin.user:
      name: roboshop
    when: output.rc != 0
  
  - name: check /app directory exists or not
    tags:
    - installation
    ansible.builtin.stat:
      path: /app
    register: directory
  
  - name: create directory
    tags:
    - installation
    ansible.builtin.file:
      path: /app
      state: directory
    when: directory.stat.exists == False
  
  - name: download catalogue artifact
    tags:
    - deployment
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
  
  - name: unzipping catalogue artifact
    tags:
    - deployment
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  
  - name: install dependencies
    tags:
    - deployment
    ansible.builtin.command: npm install
    args:
      chdir: /app
  
  - name: copy catalogue service
    tags:
    - installation
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  
  - name: daemon-reload
    tags:
    - installation
    ansible.builtin.systemd:
      daemon-reload: yes
  
  - name: copying mongo repo to yum.repos.d
    tags:
    - installation
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongodb client
    tags:
    - installation
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed
  
  - name: load catalogue data
    tags:
    - installation
    ansible.builtin.command: mongo --host 172.31.46.118 < /app/schema/catalogue.js

  - name: restart catalogue
    tags:
    - deployment
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes