- name: demo on filters
  hosts: localhost
  vars:
    NAME: Venkata Anand
    website: "https://github.com/An2an7d/ansible-advanced"
    greeting: "hello,how are you"
  tasks:
  - name: convert into upper case
    debug:
      msg: "upper case: {{NAME|upper}}"
  
  - name: convert into lower case
    debug:
      msg: "lower case: {{NAME|lower}}"

  - name: printing undefined variable
    debug:
      msg: "course is {{COURSE|default('Devops')}}"

  - name: extract hostname
    debug:
      msg: "{{website|urlsplit('hostname')}}"
  
  - name: split
    debug:
      msg: "{{greeting|split(',')}}"